var MW = MW || {};

// Show board
MW.NROWS = 8;
MW.NCOLUMNS = 8;
// Max 32
MW.NTYPES = 8;
// MW.NROWS * MW.NCOLUMNS = MW.NTYPES * MW.N_EACH_OF_TYPE
MW.N_EACH_OF_TYPE = 8;

MW.CURRENT_MODE = 0
// Easy mode
MW.INDEX_EASY = 0;
MW.NROWS_EASY = 8;
MW.NCOLUMNS_EASY = 8;
MW.NTYPES_EASY = 8;
MW.N_EACH_OF_TYPE_EASY = 8;

// Normal mode
MW.INDEX_NORMAL = 1;
MW.NROWS_NORMAL = 8;
MW.NCOLUMNS_NORMAL = 8;
MW.NTYPES_NORMAL = 32;
MW.N_EACH_OF_TYPE_NORMAL = 2;

// Hard mode
MW.INDEX_HARD = 2;
MW.NROWS_HARD = 10;
MW.NCOLUMNS_HARD = 10;
MW.NTYPES_HARD = 25;
MW.N_EACH_OF_TYPE_HARD = 4;

// Other config
MW.SOUND = true;
MW.FLAREY = 445;
MW.SCALE = 1.5;
MW.WIDTH = 480;
MW.HEIGHT = 720;
MW.FONTCOLOR = "#1f2d96";
MW.menuHeight = 36;
MW.menuWidth = 123;