var MW = MW || {};

// Show board
MW.NROWS = 4;
MW.NCOLUMNS = 4;
// Max 32
MW.NTYPES = 4;
// MW.NROWS * MW.NCOLUMNS = MW.NTYPES * MW.N_EACH_OF_TYPE
MW.N_EACH_OF_TYPE = 4;

MW.BOARD_RUN = 1

MW.CURRENT_MODE = 0
// Easy mode
MW.INDEX_EASY = 0;
MW.NROWS_EASY = 8;
MW.NCOLUMNS_EASY = 8;
MW.NTYPES_EASY = 8;
MW.N_EACH_OF_TYPE_EASY = 8;

// Normal mode
MW.INDEX_NORMAL = 1;
MW.NROWS_NORMAL = 10;
MW.NCOLUMNS_NORMAL = 10;
MW.NTYPES_NORMAL = 25;
MW.N_EACH_OF_TYPE_NORMAL = 4;

// Hard mode
MW.INDEX_HARD = 2;
MW.NROWS_HARD = 12;
MW.NCOLUMNS_HARD = 12;
MW.NTYPES_HARD = 36;
MW.N_EACH_OF_TYPE_HARD = 4;

// Choose effect
MW.DURATION_CHOOSE_EFFECT = 0.3
MW.REVERT_COLOR = {r:255, g:255, b:255}
MW.EFFECT_COLOR = {r:192, g:192, b:192}
MW.NAME_CHOOSE_POKEMON = "choosePokemon"

// Sound
MW.SOUND_VOLUMN = 0.4
MW.SOUND = true;

// Other config
MW.FLAREY = 445;
MW.SCALE = 1.5;
MW.WIDTH = 480;
MW.HEIGHT = 720;
MW.FONTCOLOR = "#1f2d96";
MW.WHITE_COLOR = "FFFFFF";
MW.menuHeight = 36;
MW.menuWidth = 123;